### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by cuongitbk** [BuiVanDuc/APReport#1]
Trong các project python cần 1 file: requirements.txt trong đó liệt kê danh sách các thư viện + phiên bản tương ứng đã sử dụng để người cài đặt hoặc phát triển biết mã nguồn được xây dựng từ môi trường như thế nào.

Ví dụ nội dung file requirements.txt

> django==2.0.7
> msgpack==0.5.6
> djangorestframework==3.8.2
> django-cors-headers==2.4.0
> django-filter==2.0.0
> psycopg2-binary==2.7.7

**Comment by BuiVanDuc** [comment]
vâng anh, trong các project khác em sẽ bổ sung
