### ISSUE TITLE
Cấu trúc project

### ISSUE THREAD

**Issue by cuongitbk** [BuiVanDuc/APReport#2]
Anh thấy cấu trúc project của em chưa ổn, còn lộn xộn:
- Thư mục app_service (hoặc tên khác tùy lúc tạo project): thư mục này sẽ chỉ chứa các file sau: wsgi.py, urls.py, settings.py
- Thư mục: database chứa file models.py
- Thư mục utils chứa các file theo tên nội dung nó thực hiện, ví dụ: file_utils.py, xlsx_utils.py, http_utils.py, ... 
- Thư mục static chứa các file tĩnh, ví dụ như tất cả báo cáo sinh ra sẽ đặt trong thư mục: static/reports
- Các folder khác liên quan trực tiếp tới các API sẽ cấu thành bởi 03 file: controller.py (hoặc là views.py), urls.py (File này có thể có hoặc không có), serializer.py (File này cũng có thể có hoặc không có)

**Lưu ý:** 
- Khi đã up lên git và gửi cho anh thì bỏ hết code rác đi, ví dụ file test.py, thư mục reports (theo code có vẻ không cần code trong thư mục này???)
- Ví dụ create_file, modify_file của em có thể cho vào file xlsx_utils.py, đổi tên và tham số đầu vào như dưới đây nhìn code trong sáng và ý nghĩa hơn:

```
def create_xlsx_file_using_template(total_number_of_sheet, file_dir=REPORT_DIR, template=None):
...
def update_xlsx_file(file_name, data, file_dir=REPORT_DIR):
...
```

**Comment by BuiVanDuc** [comment]
em sửa lại ạ

**Comment by cuongitbk** [comment]
- report/template --> static/template
- report/controller.py và report/export_controller.py sao không gộp làm 1 file? Nếu đã tách thì làm thành hai folder riêng hoặc theo dạng:

report/controller.py
report/export/controller.py

**Note:** 
- A đã comment bên trên là 1 folder liên quan trực tiếp tới API thì cấu thành bởi các file chính nào rồi đó
- Các phần cấu trúc khác coi như tạm ok

**Comment by cuongitbk** [comment]
**Về cách đặt tên hàm:**
- check_report_existing(): Nếu là hàm check thì chỉ trả về True hoặc False chứ không phải trả về danh sách
- rename_file_report_existing(): Nếu rename thì tham số đầu vào phải có tên cũ, tên mới

**Về cách code**
- datetime người ta có cách "convert to string" thành các định dạng mong muốn, chứ không phải là dùng replace, khi code phải nghĩ rồi search chứ không phải biết replace là cứ thế code. Nếu em search rất đơn giản "convert datetime to string python" thì nó ra cả tỷ kết quả

**Comment by BuiVanDuc** [comment]
em sửa lại ngay
