### ISSUE TITLE
Giải thích ý nghĩa các biến

### ISSUE THREAD

**Issue by cuongitbk** [BuiVanDuc/APReport#4]
- is_looked_for: biến này mục đích em thiết kế để làm gì?
- name: Biến này có cần thiết ko?
- crated_at: lưu ý đặt tiếng anh cho chuẩn, phải học thói quen nhìn nó sai mình ngứa mắt chứ đừng ngại nhiều chỗ quá không sửa, reformat code cái là được

**Comment by BuiVanDuc** [comment]
. is_looked_for: biến này có ý nghĩa là True khi báo cáo đã được tìm kiếm
. Name: biến này là thừa
. crated_at: phải là created_at: Biến này em sửa lại

**Comment by cuongitbk** [comment]
> . is_looked_for: biến này có ý nghĩa là True khi báo cáo đã được tìm kiếm

Đánh dấu báo cáo đã được tìm kiếm để làm gì?

**Comment by BuiVanDuc** [comment]
Theo yêu cầu của anh đưa ra là tạo báo đối với những báo cáo đã được tìm kiếm theo ngày

**Comment by cuongitbk** [comment]
Y/c ở đây mục đích là sau khi tìm kiếm thì có thể trích xuất báo cáo theo kết quả tìm kiếm. Ví dụ người dùng tìm kiếm ra 5 kết quả thì cho người ta trích xuất báo cáo 5 kết quả đó
