### ISSUE TITLE
Logic API download

### ISSUE THREAD

**Issue by cuongitbk** [BuiVanDuc/APReport#5]
1. Bản chất việc download báo cáo ở bài này sẽ phải có 02 pha:
- Pha 1: Trích xuất báo cáo
- Pha 2: Tải báo cáo về

**Mở rộng:** Ở pha 1 lại có 02 tình huống xảy ra:
- Tình huống 1: Nếu báo cáo đã tồn tại
- Tình huống 2: Báo cáo chưa tồn tại

=> Vậy với 02 tính huống này xử lý như thế nào? Và làm sao để biết báo cáo đã tồn tại?

2. Bỏ qua phần mở rộng, cách em làm (truyền biến date) cũng được nhưng logic mình có thể xử lí tốt hơn:
- Nếu date bằng None --> Coi như là tải tất cả
- Nếu date khác None, thay vì dùng hàm check_format_date, mình viết 1 hàm như: parse_date_from_string. Hàm này convert string sang date và date này sẽ truyền luôn vào hàm chỗ filter. Chứ hàm check_format_date này anh thấy vô dụng trong chỗ này???

3. Ngay vào hàm get em đã call luôn: queryset = StatisticalDataReport.objects.all() như vậy rất không hợp lí, nếu ngta chỉ truyền vào 1 ngày thì tự dưng lại phải query tất cả các dữ liệu

4. Return dữ liệu phải có ý nghĩa, ví dụ trong trường hợp này phải trả về được đường dẫn tương đối tới file báo cáo đã trích xuất.

5. Các hàm create_file, modify_file, ... phải có return giá trị trả về để còn kiểm tra xem thành công hay thất bại

**Tổng hợp lại anh có viết ví dụ hàm get như sau:**

```
def get(self, request, *args, **kwargs):
	date_str = self.request.query_params.get('date', None)
	
	if date_str:
		date = parse_date_from_string(date_str)
		if date:
			queryset = StatisticalDataReport.objects.filter(created_at__date=date)
		else:
			return Response(data={'detail': 'Invalid date string, please use date in format: %Y-%m-%d, For ex: 2019-02-11'}, status=status.HTTP_406_NOT_ACCEPTABLE)
	else:
		queryset = StatisticalDataReport.objects.all()
		
	number_sheet = queryset.count()
	if number_sheet > 0:
		# number_sheet > 1 tương đương với type_report = 2, ngược lại type_report = 3
		path_report = writing_file.create_file(number_sheet)
		if path_report: 
			relative_path = writing_file.modify_file(data_report, path_report)
			if relative_path:
				return Response(data={"path": relative_path}, status=status.HTTP_200_OK)
	else:
		return Response(data={'detail': 'No report found'}, status=status.HTTP_404_NOT_FOUND)
	return Response(data=None, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
```

**Comment by cuongitbk** [comment]
Sẽ hướng dẫn cách tư duy thoáng hơn cho module trong file export_controller.py trong tuần tới

**Comment by BuiVanDuc** [comment]
vâng anh

**Comment by cuongitbk** [comment]
@BuiVanDuc: Em nên code cẩn thận từ trên xuống dưới, dò xét kĩ lưỡng tránh tình trạng cứ muốn làm nhanh nhanh khiến có mấy dòng code mà loay hoay comment hết cái này tới cái khác

- https://github.com/BuiVanDuc/APReport/blob/4eeb0c2f860c5ddca512fba59a359ee0b0b97144/report/export/export_controller.py#L39: Chỉ 1 bản ghi bị null mà báo luôn 404 và không có dữ liệu gì sao ngta biết là cái nào bị 404?

- https://github.com/BuiVanDuc/APReport/blob/4eeb0c2f860c5ddca512fba59a359ee0b0b97144/report/export/export_controller.py#L73: Response thế này thì thằng code giao diện nó biết xử lí thế nào

- https://github.com/BuiVanDuc/APReport/blob/4eeb0c2f860c5ddca512fba59a359ee0b0b97144/report/export/export_controller.py#L78: Đã bảo khởi tạo cái ret_data trong vòng for, sao lại dùng .copy?

**Comment by cuongitbk** [comment]
Ví dụ a code sẽ như thế này:

**Serializer**
```
from rest_framework import serializers

class ExportMultiReportSerializer(serializers.Serializer):
    report_ids = serializers.ListSerializer(child=serializers.IntegerField())
	export_type = serializers.IntegerField(default=0) # 0 --> 1 Sheet in 1 File, 1 --> Multiple sheets in 1 File, 2 --> Multiple Files
	is_forced = serializers.IntegerField(default=0) # 1 --> Generated new report
```

**Controller:**
```
class ExportController(CreateAPIView):

    def post(self, request, *args, **kwargs):
        data = JSONParser().parse(request)
        serializer = ExportMultiReportSerializer(data=data)

        if serializer.is_valid():
			validated_data = serializer.validated_data
            export_type = validated_data.get('export_type')
            is_forced = validated_data.get('is_forced')
            report_ids = int(data['report_ids'])
			'''
				{
					"status": 0,			# 0 --> Report is not existed, export report failed, 1 --> Report is existed, export report failed, 2 --> Successfully
					"report_id": 1,			# Id of report
					"report_url": None		# Uri of report if exported successfully else it's None
				}
			'''
			ret_data = list()
			
			list_reports = list()
			start_date = None
			end_date = None
			for report_id in report_ids:
				try:
					report = StatisticalDataReport.objects.get(id=report_id)
					if start_date is None or start_date < report.created_at:
						start_date = report.created_at
					if end_date is None or end_date > report.created_at:
						end_date = report.created_at
				except StatisticalDataReport.DoesNotExist:
					ret_data.append({"status": 0, "report_id": report_id, "report_url": None})
			
			if len(list_reports) <= 0:
				return Response(data=ret_data, status=status.HTTP_404_NOT_FOUND)
			
			# 0 --> 1 Sheet in 1 File
			if export_type == 0:
				report_name = convert_datetime_to_string(start_date, end_date)
				if not is_file_existed(report_name) or is_forced == 1:
					# Add code here
					pass
			# 1 --> Multiple sheets in 1 File
			elif export_type == 1:
				report_name = convert_datetime_to_string(start_date, end_date)
				# Add code here
			2 --> Multiple Files
			elif export_type == 1:
				# Add code here
				pass
			else:
				return Response(data={"details": "Invalid export type"}, status=status.HTTP_406_NOT_ACCEPTABLE)
			
            return Response(data=ret_data, status=status.HTTP_200_OK)

        return Response(data=serializer.errors, status=status.HTTP_406_NOT_ACCEPTABLE)
```

**Comment by cuongitbk** [comment]
- https://github.com/BuiVanDuc/APReport/blob/90d5319dcb07d1b14dd7bd087770075aa116bda5/report/export/export_controller.py#L53
Mục đích anh đã thiết kế thằng ret_data để trả về, tại sao chỗ thì trả về None, chỗ thì chỉ có return Response (dòng 78)???. Hơn nữa cấu trúc của 1 phần tử trong ret_data lúc thì dùng status (dòng 50), lúc thì lại dùng status_report, không khớp nhau tẹo nào

- https://github.com/BuiVanDuc/APReport/blob/90d5319dcb07d1b14dd7bd087770075aa116bda5/report/export/export_controller.py#L61
Nếu report_name None hoặc len = 0 thì chuyện gì xảy ra? em đã bỏ sót không xử lí tình huống này??

- https://github.com/BuiVanDuc/APReport/blob/90d5319dcb07d1b14dd7bd087770075aa116bda5/report/export/export_controller.py#L71

Biến info_report anh thấy chẳng có tác dụng gì cả??? Mà anh đã bảo rồi, nếu chỉ dùng local thì đừng có khai báo nó là biến cục bộ.

- https://github.com/BuiVanDuc/APReport/blob/90d5319dcb07d1b14dd7bd087770075aa116bda5/report/export/export_controller.py#L77
- https://github.com/BuiVanDuc/APReport/blob/90d5319dcb07d1b14dd7bd087770075aa116bda5/report/export/export_controller.py#L94
REPORT_DIR mặc định sẽ join bởi BASE_DIR, tức là có đường dẫn tuyệt đối tới thư mục report trên máy, chứ không phải địa chỉ url của file report. Tương tự hai hàm create_xlsx_file_using_template và update_xlsx_file cũng trả về tương tự
