### ISSUE TITLE
Logic trong file export_controller.py

### ISSUE THREAD

**Issue by cuongitbk** [BuiVanDuc/APReport#6]
1. ret_data = dict() khai báo hai dòng 28 và 48

2. list_info = list() có thể khai báo trước vòng for dòng 76 vì thực tế phạm vi sử dụng của nó chỉ ở trong đó

3. Trong vòng for dòng 76, khi vào vòng for nên khởi tạo lại ret_data = dict() tránh sai lệch dữ liệu

4. Chưa thấy có kiểm tra cờ force download hay không, nếu đã tồn tại báo cáo và có cờ force download thì đơn giản là ghi đè báo cáo mới, cần gì phải đổi tên của báo cáo cũ sang 1 file mới để làm gì

5. Tên biến này có đúng ý nghĩa không: file_name_extension?

**Comment by BuiVanDuc** [comment]
4. Trường người dùng cần thông tin cũ nhưng không backup nó, em dữ lại báo cáo cũ

**Comment by BuiVanDuc** [comment]
4. trường hợp này thừa để e sửa lại ah
